@echo off
echo [*] Adding files to git...
git add .
echo [*] Committing...
git commit -m "update: prepare for gitee open source"
echo [*] Please enter your Gitee repository URL (e.g., https://gitee.com/kentoo/au-subtitle-sync.git):
set /p gitee_url=
echo [*] Adding remote 'gitee'...
git remote add gitee %gitee_url%
echo [*] Pushing to Gitee master...
git push -u gitee master
echo [!] Done!
pause
